# Generated by Django 2.0.6 on 2018-07-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=2000)),
                ('imghome', models.CharField(max_length=30)),
                ('img1', models.CharField(max_length=30)),
                ('img2', models.CharField(max_length=30)),
                ('img3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent', models.CharField(max_length=100)),
                ('wishlist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=2000)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewdestinations', to='signup.destination')),
            ],
        ),
        migrations.CreateModel(
            name='siteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='stateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewusers', to='signup.siteUser'),
        ),
        migrations.AddField(
            model_name='history',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyusers', to='signup.siteUser'),
        ),
    ]
