# Generated by Django 2.0.6 on 2018-07-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stateName',
            new_name='state',
        ),
    ]
